### ISSUE TITLE
Stuttering at end of encounter

### ISSUE THREAD

**Issue by ZacharyCarrollAshl** [UnknownX7/NoClippy#52] opened 2023-10-21 01:02 UTC
Whenever I pull an enemy with NoClippy on, my game stutters after the enemy dies. I'm sure it is NoClippy as I've turned every other mod off and it is only happening when NoClippy is enabled.

**Comment by RadicalInquisitor** [comment] 2023-10-24 15:59
Can confirm this as well.

**Comment by grantwwu** [comment] 2023-10-30 22:09
Dupe of #51

**Closed** 2024-07-04 20:26 UTC
