### ISSUE TITLE
Using Meikyo Shisui does not highlight GCDs

### ISSUE THREAD

**Issue by Okayu002** [UnknownX7/NoClippy#32] opened 2022-08-25 13:38 UTC
![image](https://user-images.githubusercontent.com/112094916/186679131-5199484f-89ee-42ff-b7e4-d802b25c84ad.png)

After the 6.2 update everytime i log into the game my meikyo never highlight my gcds, the only plugin im using is noclippy, ive tried restarting the game and even restarting my pc, and it still is bugged. Its only a visual bug but its very weird using it without the highlight.

**Comment by ichi-obi** [comment] 2022-08-25 15:54
can confirm its not working for me too

**Comment by SolidDesu** [comment] 2022-08-25 16:44
Can confirm it's not working for me also

**Comment by byte-warlock** [comment] 2022-08-25 17:47
I can also confirm this. I tested with the plugin enabled but with all options disabled and the issue persisted. Only disabling the plugin entirely from the plugin list fixes the issue.

**Comment by UnknownX7** [comment] 2022-08-26 05:08
Duplicate of #3

**Closed by UnknownX7** 2022-08-26 05:08 UTC
